sonar.projectKey=UPT-FAING-EPIS_proyecto-si784-2026-i-u3-ids-sistema-deteccion-de-instrusos_u3
sonar.organization=upt-faing-epis
sonar.projectName=TrafficWatch IDS
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

sonar.sources=src,web,main.py,run_dashboard.py,trafficwatch_desktop.py
sonar.tests=tests,tests_ui,tests_mutation
sonar.python.version=3.11
sonar.exclusions=logs/**,mutants/**,reports/**,docs/**,media/**,installer_output/**,dist/**
sonar.python.coverage.reportPaths=coverage.xml
